### ISSUE TITLE
Argument separator from LogDuckSettings is ignored.

### ISSUE THREAD

**Issue by lrsp** [ZeeWeasel/LogDuck#2]
This is because in LogDuck.gd you have this code, which redefines **seperator**, ignoring the previously defined setting.

I suggest you change the setting to **separator_type**

```
    var seperator : String # Overwrites the separator setting.
    
    match seperator:
        SeperatorType.SPACE:
            seperator = " "
        SeperatorType.COMMA:
            seperator = ", "
        SeperatorType.PIPE:
            seperator = " | "

```

**Comment by ZeeWeasel** [comment]
Good catch & good suggestion! Renamed the settings variable to seperator_type
