### ISSUE TITLE
Logging from editor script

### ISSUE THREAD

**Issue by Supamiu** [ZeeWeasel/LogDuck#4]
When creating a `@tool` script, it's not possible to access `LogDuck` as an autloaded script because it's missing the `@tool` decorator, showing a null error.

**Comment by ZeeWeasel** [comment]
Good catch! I didn't consider that someone would want to use it in an editor script. 

It's a bit of an odd workaround, but I found a way to load the singleton in the editor like this:
https://github.com/godotengine/godot/issues/4236#issuecomment-1256978858

The only issue is that get_stack(), if called in the editor, does not return anything. I still need to figure out how to read the classname from scripts in the editor or get the path of the script. Maybe someone else has an idea how to make that work for editor scripts!
